version: "3.8"
services:
    db:
        networks:
            - test
        build: database/.
        restart: always

    server:
        depends_on:
            - db
        restart: always
        networks:
            - test
        build: flaskServer/.
        ports:
            - 5000:80
          


networks:
    test:
        driver: bridge
