version: "3.8"
services:
    db:
        networks:
            - test
        build: database/.
        restart: always
        #volumes:
        #    - ./database/mount:/var/lib/mysql

    server:
        depends_on:
            - db
        restart: always
        networks:
            - test
        build: flaskServer/.
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
          
networks:
    test:
        driver: bridge